### ISSUE TITLE
Remote Server Notice Source Wrong

### ISSUE THREAD

**Issue by jobe1986** [evilnet/nefarious2#29]
Need to update server notice distribution to show the correct source server (apply HIS_REWRITE?)

**Comment by frootv** [comment]
dear jobe: i just found some post submitted by some guy 10 years ago regarding HIS_MODEWHO:
http://sourceforge.net/p/undernet-ircu/bugs/81/
and kevin said that it wasn't a bug but is a feature that a by-design so that it will really show which oper made the mode changes. but in my opinion, although the command is "opmode", there should be the server that make mode changes and not the oper that will make it look like weird :dancer:

i am looking at the channel.c where line
    app_source = &his;
  else
    app_source = mbuf->mb_source;

when you use a services to change the mode where services itself use their server to change a mode, it appear as a services server name.

i think that m_opmode.c need to be modified so that mbuf->mb_source; think that it made the mode change and not oper that execute the command did that.
i try to change app_source = &me;
didn't work. it appear the local server name, but other server servers that linked display their servername did mode change, and not originating servers :dancer:

**Comment by jobe1986** [comment]
Fixed in revision 5e0a8ce1cd1e473daf2505f8b4cb6b1f4f6e091e
