### ISSUE TITLE
This server was created Sat Jan 10 2015 at 13:51:55 EST

### ISSUE THREAD

**Issue by WildClaudio** [evilnet/nefarious2#33]
Hello i have a silly request or maybe someone can ... guide to the right lines where the source is writing the "server creation time" as my dedicated got restarted so now my server creation got a new DATE as the ircd proccess got killed 

my question/request is :if there is a way to keep the server date creation when the server/ircd process started for the first time and not restarting it every time when the proccess is killed/server rebooted ....  running on a network with over 25 servers using nefarious2 after the "ghost" vuln in some Linux distros , looks now like a young network almost  all servers have creation date 2015 not really a bug/issue ..and doesnt affect the source integrity its more like a "feature" :) 

thank you in advance !!!

**Comment by jobe1986** [comment]
The date to which you refer is in fact the date the IRCd was last compiled. It is not the date it was last started. So if that date has changed as the result of restarting the IRCd its because you recompiled the IRCd but failed to restart it as is necessary. Not to mention given that date is the compile date it's also useful as an indicator to your users that you are keeping the IRCd up to date and thus in turn as secure as possible. Basically if the date remains an old date then your users can think you haven't recompiled the IRCd after updating system libraries and can in turn lead them to believe it is still insecure.

As for where the date comes from, the "make" step of the compile process runs a script called version.c.SH which generates a version.c, in that version.c is the date the script was run.

Hope this helps you better understand the purpose of the date.
